import { CardData } from '@/types/types';

const cardData: CardData = {
  'red-zero': {
    id: 0,
    color: 'red',
    description: '0',
    effect: null,
    points: 0,
    countOfCards: 1,
  },
  'red-one': {
    id: 1,
    color: 'red',
    description: '1',
    effect: null,
    points: 1,
    countOfCards: 2,
  },
  'red-two': {
    id: 2,
    color: 'red',
    description: '2',
    effect: null,
    points: 2,
    countOfCards: 2,
  },
  'red-three': {
    id: 3,
    color: 'red',
    description: '3',
    effect: null,
    points: 3,
    countOfCards: 2,
  },
  'red-four': {
    id: 4,
    color: 'red',
    description: '4',
    effect: null,
    points: 4,
    countOfCards: 2,
  },
  'red-five': {
    id: 5,
    color: 'red',
    description: '5',
    effect: null,
    points: 5,
    countOfCards: 2,
  },
  'red-six': {
    id: 6,
    color: 'red',
    description: '6',
    effect: null,
    points: 6,
    countOfCards: 2,
  },
  'red-seven': {
    id: 7,
    color: 'red',
    description: '7',
    effect: null,
    points: 7,
    countOfCards: 2,
  },
  'red-eight': {
    id: 8,
    color: 'red',
    description: '8',
    effect: null,
    points: 8,
    countOfCards: 2,
  },
  'red-nine': {
    id: 9,
    color: 'red',
    description: '9',
    effect: null,
    points: 9,
    countOfCards: 2,
  },
  'red-skip': {
    id: 10,
    color: 'red',
    description: 'skip',
    effect: 'skip',
    points: 20,
    countOfCards: 2,
  },
  'red-reverse': {
    id: 11,
    color: 'red',
    description: 'reverse',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },
  'red-draw2': {
    id: 12,
    color: 'red',
    description: 'draw2',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },

  'yellow-zero': {
    id: 13,
    color: 'yellow',
    description: '0',
    effect: null,
    points: 0,
    countOfCards: 1,
  },
  'yellow-one': {
    id: 14,
    color: 'yellow',
    description: '1',
    effect: null,
    points: 1,
    countOfCards: 2,
  },
  'yellow-two': {
    id: 15,
    color: 'yellow',
    description: '2',
    effect: null,
    points: 2,
    countOfCards: 2,
  },
  'yellow-three': {
    id: 16,
    color: 'yellow',
    description: '3',
    effect: null,
    points: 3,
    countOfCards: 2,
  },
  'yellow-four': {
    id: 17,
    color: 'yellow',
    description: '4',
    effect: null,
    points: 4,
    countOfCards: 2,
  },
  'yellow-five': {
    id: 18,
    color: 'yellow',
    description: '5',
    effect: null,
    points: 5,
    countOfCards: 2,
  },
  'yellow-six': {
    id: 19,
    color: 'yellow',
    description: '6',
    effect: null,
    points: 6,
    countOfCards: 2,
  },
  'yellow-seven': {
    id: 20,
    color: 'yellow',
    description: '7',
    effect: null,
    points: 7,
    countOfCards: 2,
  },
  'yellow-eight': {
    id: 21,
    color: 'yellow',
    description: '8',
    effect: null,
    points: 8,
    countOfCards: 2,
  },
  'yellow-nine': {
    id: 22,
    color: 'yellow',
    description: '9',
    effect: null,
    points: 9,
    countOfCards: 2,
  },
  'yellow-skip': {
    id: 23,
    color: 'yellow',
    description: 'skip',
    effect: 'skip',
    points: 20,
    countOfCards: 2,
  },
  'yellow-reverse': {
    id: 24,
    color: 'yellow',
    description: 'reverse',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },
  'yellow-draw2': {
    id: 25,
    color: 'yellow',
    description: 'draw2',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },

  'green-zero': {
    id: 26,
    color: 'green',
    description: '0',
    effect: null,
    points: 0,
    countOfCards: 1,
  },
  'green-one': {
    id: 27,
    color: 'green',
    description: '1',
    effect: null,
    points: 1,
    countOfCards: 2,
  },
  'green-two': {
    id: 28,
    color: 'green',
    description: '2',
    effect: null,
    points: 2,
    countOfCards: 2,
  },
  'green-three': {
    id: 29,
    color: 'green',
    description: '3',
    effect: null,
    points: 3,
    countOfCards: 2,
  },
  'green-four': {
    id: 30,
    color: 'green',
    description: '4',
    effect: null,
    points: 4,
    countOfCards: 2,
  },
  'green-five': {
    id: 31,
    color: 'green',
    description: '5',
    effect: null,
    points: 5,
    countOfCards: 2,
  },
  'green-six': {
    id: 32,
    color: 'green',
    description: '6',
    effect: null,
    points: 6,
    countOfCards: 2,
  },
  'green-seven': {
    id: 33,
    color: 'green',
    description: '7',
    effect: null,
    points: 7,
    countOfCards: 2,
  },
  'green-eight': {
    id: 34,
    color: 'green',
    description: '8',
    effect: null,
    points: 8,
    countOfCards: 2,
  },
  'green-nine': {
    id: 35,
    color: 'green',
    description: '9',
    effect: null,
    points: 9,
    countOfCards: 2,
  },
  'green-skip': {
    id: 36,
    color: 'green',
    description: 'skip',
    effect: 'skip',
    points: 20,
    countOfCards: 2,
  },
  'green-reverse': {
    id: 37,
    color: 'green',
    description: 'reverse',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },
  'green-draw2': {
    id: 38,
    color: 'green',
    description: 'draw2',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },

  'blue-zero': {
    id: 39,
    color: 'blue',
    description: '0',
    effect: null,
    points: 0,
    countOfCards: 1,
  },
  'blue-one': {
    id: 40,
    color: 'blue',
    description: '1',
    effect: null,
    points: 1,
    countOfCards: 2,
  },
  'blue-two': {
    id: 41,
    color: 'blue',
    description: '2',
    effect: null,
    points: 2,
    countOfCards: 2,
  },
  'blue-three': {
    id: 42,
    color: 'blue',
    description: '3',
    effect: null,
    points: 3,
    countOfCards: 2,
  },
  'blue-four': {
    id: 43,
    color: 'blue',
    description: '4',
    effect: null,
    points: 4,
    countOfCards: 2,
  },
  'blue-five': {
    id: 44,
    color: 'blue',
    description: '5',
    effect: null,
    points: 5,
    countOfCards: 2,
  },
  'blue-six': {
    id: 45,
    color: 'blue',
    description: '6',
    effect: null,
    points: 6,
    countOfCards: 2,
  },
  'blue-seven': {
    id: 46,
    color: 'blue',
    description: '7',
    effect: null,
    points: 7,
    countOfCards: 2,
  },
  'blue-eight': {
    id: 47,
    color: 'blue',
    description: '8',
    effect: null,
    points: 8,
    countOfCards: 2,
  },
  'blue-nine': {
    id: 48,
    color: 'blue',
    description: '9',
    effect: null,
    points: 9,
    countOfCards: 2,
  },
  'blue-skip': {
    id: 49,
    color: 'blue',
    description: 'skip',
    effect: 'skip',
    points: 20,
    countOfCards: 2,
  },
  'blue-reverse': {
    id: 50,
    color: 'blue',
    description: 'reverse',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },
  'blue-draw2': {
    id: 51,
    color: 'blue',
    description: 'draw2',
    effect: 'reverse',
    points: 20,
    countOfCards: 2,
  },

  wild: {
    id: 52,
    color: null,
    description: 'changeColor',
    effect: 'changeColor',
    points: 50,
    countOfCards: 4,
  },
  wildDraw4: {
    id: 53,
    color: null,
    description: 'draw4Cards',
    effect: 'changeColor draw4',
    points: 50,
    countOfCards: 4,
  },
};

export default cardData;
